#!/bin/bash -l
#SBATCH --chdir /home/salauen/Project_I/logs
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 16
#SBATCH --mem 64G
#SBATCH --partition gpu
#SBATCH --gres gpu:1
#SBATCH --time 00:05:00
#SBATCH --qos gpu_free

echo STARTING AT `date`
echo activating environement

module load gcc cuda cudnn py-torch/1.6.0-cuda-openmp py-torchvision/0.6.1 py-torchmetrics/0.10.3
srun python3 /home/salauen/Project_I/Code/Code/Runner.py

echo Run Done